// Curated multi-tier pins dataset with official tree counts (BMC Tree Census & Forest Survey of India)
// Covers All Indian States (Maharashtra, Rajasthan, Gujarat, Delhi, UP, MP, Karnataka, Tamil Nadu, Telangana, West Bengal, etc.)

const SEED_PINS = [
  // ==========================================
  // LEVEL 1: NATIONAL PINS (Visible when whole India is focused)
  // ==========================================
  {
    id: "PIN_NAT_001",
    type: "hotspot",
    name: "Vidarbha Extreme Heat Corridor",
    heat_risk: 92,
    lst_celsius: 46.2,
    tree_count: 24500,
    tree_source: "Forest Survey of India (FSI)",
    population: "Critical Exposure",
    level: "country",
    parentId: "india",
    stateId: "maharashtra",
    coordinates: { lng: 79.0882, lat: 21.1458 },
    details: "Inland basalt basin traps extreme thermal radiation with prolonged dry heatwaves exceeding 46°C.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_NAT_002",
    type: "hotspot",
    name: "Thar Desert Arid Apex",
    heat_risk: 94,
    lst_celsius: 48.0,
    tree_count: 8200,
    tree_source: "Forest Survey of India (FSI)",
    population: "High Risk",
    level: "country",
    parentId: "india",
    stateId: "rajasthan",
    coordinates: { lng: 71.91, lat: 26.91 },
    details: "Extreme desert surface heating with high diurnal flux and acute water scarcity.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_NAT_003",
    type: "cooling_centre",
    name: "Ahmedabad Civil Hospital Heat Hub",
    heat_risk: 48,
    lst_celsius: 38.0,
    tree_count: 18400,
    tree_source: "Ahmedabad AMC Tree Registry",
    population: "1,200 Beds Capacity",
    level: "country",
    parentId: "india",
    stateId: "gujarat",
    coordinates: { lng: 72.602, lat: 23.053 },
    details: "Dedicated Heat Action Plan triage hub with specialized cooling wards and cold water distribution.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },
  {
    id: "PIN_NAT_004",
    type: "cooling_centre",
    name: "Delhi AIIMS Apex Thermal Respite",
    heat_risk: 52,
    lst_celsius: 39.5,
    tree_count: 32000,
    tree_source: "Delhi Forest Dept Census",
    population: "850 Beds Capacity",
    level: "country",
    parentId: "india",
    stateId: "delhi",
    coordinates: { lng: 77.209, lat: 28.567 },
    details: "Central heat emergency casualty wing with rapid misting pods and oral rehydration logistics.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },
  {
    id: "PIN_NAT_005",
    type: "water_needed",
    name: "Bundelkhand Drought Buffer",
    heat_risk: 89,
    lst_celsius: 45.4,
    tree_count: 14200,
    tree_source: "FSI Regional Canopy Audit",
    population: "Severe Drought Deficit",
    level: "country",
    parentId: "india",
    stateId: "uttar-pradesh",
    coordinates: { lng: 78.58, lat: 25.45 },
    details: "Acute groundwater depletion causing extreme dehydration distress for agricultural transit laborers.",
    action_label: "Plan Water Kiosks",
    action_type: "whatif",
  },
  {
    id: "PIN_NAT_006",
    type: "low_veg",
    name: "Rayalaseema Scrubland Deficit",
    heat_risk: 85,
    lst_celsius: 44.1,
    tree_count: 11500,
    tree_source: "FSI Canopy Survey",
    population: "High Vulnerability",
    level: "country",
    parentId: "india",
    stateId: "andhra-pradesh",
    coordinates: { lng: 77.6, lat: 14.68 },
    details: "Semi-arid rain-shadow plateau requiring massive green corridor tree plantation to block thermal winds.",
    action_label: "Simulate Greening",
    action_type: "whatif",
  },
  {
    id: "PIN_NAT_007",
    type: "vulnerability",
    name: "Marathwada Rural Heat Stress Zone",
    heat_risk: 90,
    lst_celsius: 45.8,
    tree_count: 9800,
    tree_source: "Maharashtra Forest Dept",
    population: "High Outdoor Workforce",
    level: "country",
    parentId: "india",
    stateId: "maharashtra",
    coordinates: { lng: 76.85, lat: 19.1 },
    details: "High proportion of rural agrarian workers exposed to sustained wet-bulb temperatures above 33°C.",
    action_label: "Inspect Vulnerability",
    action_type: "xai",
  },
  {
    id: "PIN_NAT_008",
    type: "citizen_report",
    name: "Central Kolkata Dense Heat SOS",
    heat_risk: 87,
    lst_celsius: 41.8,
    tree_count: 6500,
    tree_source: "KMC Green Census",
    population: "14 Active Distress Alerts",
    level: "country",
    parentId: "india",
    stateId: "west-bengal",
    coordinates: { lng: 88.3639, lat: 22.5726 },
    details: "Multiple crowdsourced fainting and heatstroke alerts from dense commercial transit junctions.",
    action_label: "Review Distress Triage",
    action_type: "report",
  },

  // ==========================================
  // LEVEL 2: STATE PINS (Across ALL Indian States)
  // Visible when that state is focused -> shows district pins!
  // ==========================================

  // --- MAHARASHTRA DISTRICTS ---
  {
    id: "PIN_MH_MUM_001",
    type: "hotspot",
    name: "Mumbai Coastal Tin Roof Hotspot",
    heat_risk: 88,
    lst_celsius: 42.4,
    tree_count: 4200,
    tree_source: "BMC Tree Census Ward G/North",
    population: "High Density",
    level: "state",
    parentId: "maharashtra",
    districtId: "mumbai",
    coordinates: { lng: 72.856, lat: 19.043 },
    details: "Informal corrugated metal sheet roofs trap solar heat with high humidity and minimal shade.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_MH_THA_001",
    type: "vulnerability",
    name: "Thane Industrial Heat Corridor",
    heat_risk: 84,
    lst_celsius: 41.8,
    tree_count: 6800,
    tree_source: "TMC Urban Forest Census",
    population: "High Industrial Exposure",
    level: "state",
    parentId: "maharashtra",
    districtId: "thane",
    coordinates: { lng: 72.978, lat: 19.218 },
    details: "High concentration of metal fabricating workshops and heavy vehicular arterial traffic.",
    action_label: "Inspect Vulnerability",
    action_type: "xai",
  },
  {
    id: "PIN_MH_PUN_001",
    type: "cooling_centre",
    name: "Sassoon Hospital Regional Cooling Hub (Pune)",
    heat_risk: 45,
    lst_celsius: 36.8,
    tree_count: 12400,
    tree_source: "PMC Urban Forestry Dept",
    population: "450 Beds Capacity",
    level: "state",
    parentId: "maharashtra",
    districtId: "pune",
    coordinates: { lng: 73.874, lat: 18.528 },
    details: "Air-conditioned emergency triage with hydration kiosks and active cooling ambulances.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },
  {
    id: "PIN_MH_NAG_001",
    type: "hotspot",
    name: "Nagpur Inland Basalt Furnace",
    heat_risk: 93,
    lst_celsius: 46.5,
    tree_count: 15300,
    tree_source: "NMC Tree Authority",
    population: "Critical Exposure",
    level: "state",
    parentId: "maharashtra",
    districtId: "nagpur",
    coordinates: { lng: 79.088, lat: 21.146 },
    details: "Intense dry continentality creates asphalt temperatures exceeding 54°C in mid-afternoon.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_MH_NAS_001",
    type: "low_veg",
    name: "Nashik Godavari Basin Canopy Deficit",
    heat_risk: 76,
    lst_celsius: 39.8,
    tree_count: 8900,
    tree_source: "Nashik Forest Division",
    population: "Moderate Risk",
    level: "state",
    parentId: "maharashtra",
    districtId: "nashik",
    coordinates: { lng: 73.789, lat: 19.997 },
    details: "Loss of riverbank riparian vegetation elevates microclimate temperatures along pilgrim walkways.",
    action_label: "Simulate Greening",
    action_type: "whatif",
  },
  {
    id: "PIN_MH_SOL_001",
    type: "water_needed",
    name: "Solapur Textile Transit Water Deficit",
    heat_risk: 89,
    lst_celsius: 44.8,
    tree_count: 5200,
    tree_source: "Solapur Municipal Corp",
    population: "Acute Dehydration",
    level: "state",
    parentId: "maharashtra",
    districtId: "solapur",
    coordinates: { lng: 75.906, lat: 17.659 },
    details: "Dry arid winds and lack of public water dispensers for power-loom workers.",
    action_label: "Plan Water Kiosks",
    action_type: "whatif",
  },
  {
    id: "PIN_MH_AUR_001",
    type: "citizen_report",
    name: "Chhatrapati Sambhajinagar Distress Hub",
    heat_risk: 83,
    lst_celsius: 42.2,
    tree_count: 7400,
    tree_source: "CSMC Tree Census",
    population: "6 Active SOS Alerts",
    level: "state",
    parentId: "maharashtra",
    districtId: "aurangabad",
    coordinates: { lng: 75.343, lat: 19.876 },
    details: "Reports of elderly dizziness and bus queue dehydration near central bus terminals.",
    action_label: "Review Distress Triage",
    action_type: "report",
  },
  {
    id: "PIN_MH_CHA_001",
    type: "hotspot",
    name: "Chandrapur Coal Belt Thermal Apex",
    heat_risk: 95,
    lst_celsius: 47.1,
    tree_count: 4800,
    tree_source: "FSI Chandrapur Division",
    population: "Severe Industrial Heat",
    level: "state",
    parentId: "maharashtra",
    districtId: "chandrapur",
    coordinates: { lng: 79.296, lat: 19.961 },
    details: "Open-cast thermal coal mining and black rock radiation produce state-highest temperatures.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_MH_KOL_001",
    type: "cooling_centre",
    name: "Kolhapur CPR Civil Hospital Shelter",
    heat_risk: 54,
    lst_celsius: 37.4,
    tree_count: 14100,
    tree_source: "KMC Forestry Wing",
    population: "300 Beds Capacity",
    level: "state",
    parentId: "maharashtra",
    districtId: "kolhapur",
    coordinates: { lng: 74.243, lat: 16.705 },
    details: "District-level cooling facility serving sugar-cane agricultural workers.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },
  {
    id: "PIN_MH_JAL_001",
    type: "vulnerability",
    name: "Jalgaon Banana Basin Heat Vulnerability",
    heat_risk: 90,
    lst_celsius: 45.2,
    tree_count: 7100,
    tree_source: "Jalgaon District Forestry",
    population: "Extreme Rural Heat",
    level: "state",
    parentId: "maharashtra",
    districtId: "jalgaon",
    coordinates: { lng: 75.562, lat: 21.007 },
    details: "Intense solar exposure across unshaded agricultural plains with frequent heatwaves.",
    action_label: "Inspect Vulnerability",
    action_type: "xai",
  },

  // --- RAJASTHAN DISTRICTS ---
  {
    id: "PIN_RJ_JAI_001",
    type: "hotspot",
    name: "Jaipur Walled City Thermal Apex",
    heat_risk: 91,
    lst_celsius: 46.2,
    tree_count: 18500,
    tree_source: "Forest Survey of India (Jaipur)",
    population: "High Density Urban Heat",
    level: "state",
    parentId: "rajasthan",
    districtId: "jaipur",
    coordinates: { lng: 75.7873, lat: 26.9124 },
    details: "High thermal retention in dense pink sandstone corridors with minimal afternoon wind relief.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_RJ_JOD_001",
    type: "hotspot",
    name: "Jodhpur Sun City Arid Hotspot",
    heat_risk: 94,
    lst_celsius: 47.4,
    tree_count: 9200,
    tree_source: "FSI Jodhpur Forest Range",
    population: "Severe Arid Exposure",
    level: "state",
    parentId: "rajasthan",
    districtId: "jodhpur",
    coordinates: { lng: 73.0243, lat: 26.2389 },
    details: "Direct unshaded sunlight heating stone masonry roofs up to 52°C.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_RJ_JAI_002",
    type: "hotspot",
    name: "Jaisalmer Thar Sand Dune Furnace",
    heat_risk: 96,
    lst_celsius: 48.6,
    tree_count: 3400,
    tree_source: "FSI Arid Forest Division",
    population: "Extreme Desert Heat",
    level: "state",
    parentId: "rajasthan",
    districtId: "jaisalmer",
    coordinates: { lng: 70.916, lat: 26.9157 },
    details: "Peak desert surface radiation with barren sands and intense desiccating Loo winds.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_RJ_BIK_001",
    type: "water_needed",
    name: "Bikaner Camel Corridor Water Deficit",
    heat_risk: 92,
    lst_celsius: 47.1,
    tree_count: 4100,
    tree_source: "Bikaner Municipal Corp",
    population: "Acute Water Deficit",
    level: "state",
    parentId: "rajasthan",
    districtId: "bikaner",
    coordinates: { lng: 73.3119, lat: 28.0229 },
    details: "Acute dehydration hotspot for rural transport laborers and outdoor livestock workers.",
    action_label: "Plan Water Kiosks",
    action_type: "whatif",
  },
  {
    id: "PIN_RJ_UDA_001",
    type: "low_veg",
    name: "Udaipur Lake Basin Shading Corridor",
    heat_risk: 68,
    lst_celsius: 41.5,
    tree_count: 28400,
    tree_source: "FSI Aravalli Forest Survey",
    population: "Moderate Risk",
    level: "state",
    parentId: "rajasthan",
    districtId: "udaipur",
    coordinates: { lng: 73.7125, lat: 24.5854 },
    details: "Aravalli hillside vegetation buffers water temperature, though urban core lacks street shading.",
    action_label: "Simulate Greening",
    action_type: "whatif",
  },
  {
    id: "PIN_RJ_KOT_001",
    type: "cooling_centre",
    name: "Kota Chambal River Basin Respite Hub",
    heat_risk: 55,
    lst_celsius: 43.8,
    tree_count: 14200,
    tree_source: "Kota Municipal Tree Board",
    population: "500 Beds Capacity",
    level: "state",
    parentId: "rajasthan",
    districtId: "kota",
    coordinates: { lng: 75.8648, lat: 25.2138 },
    details: "Designated student and transit passenger thermal respite center with misting and hydration.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },

  // --- GUJARAT DISTRICTS ---
  {
    id: "PIN_GJ_AHM_001",
    type: "cooling_centre",
    name: "Ahmedabad Civil Hospital Heat Action Hub",
    heat_risk: 48,
    lst_celsius: 38.0,
    tree_count: 21000,
    tree_source: "Ahmedabad AMC Tree Census",
    population: "1,200 Beds Capacity",
    level: "state",
    parentId: "gujarat",
    districtId: "ahmedabad",
    coordinates: { lng: 72.602, lat: 23.053 },
    details: "Pioneering South Asian Heat Action Plan operational emergency triage hub.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },
  {
    id: "PIN_GJ_SUR_001",
    type: "vulnerability",
    name: "Surat Textile Industrial Heat Island",
    heat_risk: 86,
    lst_celsius: 43.2,
    tree_count: 12400,
    tree_source: "SMC Urban Environment Dept",
    population: "High Workforce Density",
    level: "state",
    parentId: "gujarat",
    districtId: "surat",
    coordinates: { lng: 72.8311, lat: 21.1702 },
    details: "Heavy industrial looms and synthetic weaving units operating with minimal roof albedo.",
    action_label: "Inspect Vulnerability",
    action_type: "xai",
  },
  {
    id: "PIN_GJ_VAD_001",
    type: "low_veg",
    name: "Vadodara Sayaji Riparian Buffer",
    heat_risk: 72,
    lst_celsius: 42.1,
    tree_count: 19800,
    tree_source: "VMC Tree Authority",
    population: "Moderate Heat",
    level: "state",
    parentId: "gujarat",
    districtId: "vadodara",
    coordinates: { lng: 73.1812, lat: 22.3072 },
    details: "Vishwamitri river corridor requires expanded urban wetland canopy to mitigate urban heat islands.",
    action_label: "Simulate Greening",
    action_type: "whatif",
  },
  {
    id: "PIN_GJ_RAJ_001",
    type: "hotspot",
    name: "Rajkot Saurashtra Arid Core",
    heat_risk: 90,
    lst_celsius: 45.4,
    tree_count: 8700,
    tree_source: "RMC Forestry Registry",
    population: "High Vulnerability",
    level: "state",
    parentId: "gujarat",
    districtId: "rajkot",
    coordinates: { lng: 70.8022, lat: 22.3039 },
    details: "Inland peninsular solar radiation with high asphalt heat absorption.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },

  // --- DELHI / NCR DISTRICTS ---
  {
    id: "PIN_DL_CEN_001",
    type: "hotspot",
    name: "Connaught Place Commercial Heat Island",
    heat_risk: 90,
    lst_celsius: 45.2,
    tree_count: 11200,
    tree_source: "NDMC Tree Census",
    population: "High Footfall Transit",
    level: "state",
    parentId: "delhi",
    districtId: "central-delhi",
    coordinates: { lng: 77.2167, lat: 28.6333 },
    details: "High vehicular congestion, asphalt radiation, and air conditioning compressor heat rejection.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_DL_SOU_001",
    type: "cooling_centre",
    name: "AIIMS South Delhi Apex Respite",
    heat_risk: 50,
    lst_celsius: 39.2,
    tree_count: 26000,
    tree_source: "Delhi Forest Dept",
    population: "850 Beds Capacity",
    level: "state",
    parentId: "delhi",
    districtId: "south-delhi",
    coordinates: { lng: 77.209, lat: 28.567 },
    details: "Apex national heat emergency medical ward with cold water immersion tanks.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },
  {
    id: "PIN_DL_NEW_001",
    type: "low_veg",
    name: "Lutyens Delhi Canopy Heritage Zone",
    heat_risk: 62,
    lst_celsius: 39.8,
    tree_count: 48000,
    tree_source: "NDMC Urban Forestry Dept",
    population: "Dense Green Buffer",
    level: "state",
    parentId: "delhi",
    districtId: "new-delhi",
    coordinates: { lng: 77.21, lat: 28.61 },
    details: "High-density mature neem and tamarind tree avenue provides 4.2°C ambient cooling.",
    action_label: "Simulate Greening",
    action_type: "whatif",
  },

  // --- KARNATAKA DISTRICTS ---
  {
    id: "PIN_KA_BLR_001",
    type: "hotspot",
    name: "Bengaluru Tech Corridor Heat Island",
    heat_risk: 78,
    lst_celsius: 38.2,
    tree_count: 32000,
    tree_source: "BBMP Tree Census 2024",
    population: "High Density IT Corridor",
    level: "state",
    parentId: "karnataka",
    districtId: "bengaluru-urban",
    coordinates: { lng: 77.5946, lat: 12.9716 },
    details: "Rapid loss of lake wetlands and asphalt sprawl elevates suburban thermal readings.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },
  {
    id: "PIN_KA_MYS_001",
    type: "low_veg",
    name: "Mysuru Chamundi Green Buffer",
    heat_risk: 58,
    lst_celsius: 35.2,
    tree_count: 41000,
    tree_source: "MCC Forest Division",
    population: "Moderate Risk",
    level: "state",
    parentId: "karnataka",
    districtId: "mysuru",
    coordinates: { lng: 76.6394, lat: 12.2958 },
    details: "Hillside deciduous forest mitigates urban temperatures across palace heritage promenades.",
    action_label: "Simulate Greening",
    action_type: "whatif",
  },

  // --- TAMIL NADU DISTRICTS ---
  {
    id: "PIN_TN_CHE_001",
    type: "hotspot",
    name: "Chennai George Town Coastal Furnace",
    heat_risk: 89,
    lst_celsius: 42.8,
    tree_count: 14500,
    tree_source: "GCC Greater Chennai Tree Census",
    population: "High Coastal Humidity",
    level: "state",
    parentId: "tamil-nadu",
    districtId: "chennai",
    coordinates: { lng: 80.2707, lat: 13.0827 },
    details: "Deadly combination of 85% relative humidity and 42°C ground heat pushing WBGT above 34°C.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },

  // --- TELANGANA DISTRICTS ---
  {
    id: "PIN_TG_HYD_001",
    type: "hotspot",
    name: "Hyderabad Charminar Old City Hotspot",
    heat_risk: 88,
    lst_celsius: 44.1,
    tree_count: 17500,
    tree_source: "GHMC Urban Biodiversity Wing",
    population: "High Density Settlement",
    level: "state",
    parentId: "telangana",
    districtId: "hyderabad",
    coordinates: { lng: 78.4744, lat: 17.3616 },
    details: "Dense basalt bedrock and narrow alleyways trap radiant thermal energy.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },

  // --- UTTAR PRADESH DISTRICTS ---
  {
    id: "PIN_UP_LKO_001",
    type: "cooling_centre",
    name: "Lucknow KGMU Thermal Casualty Center",
    heat_risk: 54,
    lst_celsius: 39.8,
    tree_count: 22000,
    tree_source: "LMC Tree Authority",
    population: "600 Beds Capacity",
    level: "state",
    parentId: "uttar-pradesh",
    districtId: "lucknow",
    coordinates: { lng: 80.9462, lat: 26.8467 },
    details: "Central heatstroke ICU facility equipped with ice bath immersion equipment.",
    action_label: "View Cooling Hub",
    action_type: "coolpath",
  },
  {
    id: "PIN_UP_KAN_001",
    type: "hotspot",
    name: "Kanpur Industrial Heat Belt",
    heat_risk: 92,
    lst_celsius: 46.2,
    tree_count: 8400,
    tree_source: "FSI Kanpur Forest Range",
    population: "High Labor Vulnerability",
    level: "state",
    parentId: "uttar-pradesh",
    districtId: "kanpur-nagar",
    coordinates: { lng: 80.3319, lat: 26.4499 },
    details: "Dense unshaded tanneries and metal casting workshops causing acute heat exhaustion.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },

  // --- WEST BENGAL DISTRICTS ---
  {
    id: "PIN_WB_KOL_001",
    type: "hotspot",
    name: "Kolkata BBD Bagh Concrete Heat Island",
    heat_risk: 88,
    lst_celsius: 41.5,
    tree_count: 14500,
    tree_source: "KMC Green Census",
    population: "Extreme Humidity Stress",
    level: "state",
    parentId: "west-bengal",
    districtId: "kolkata",
    coordinates: { lng: 88.3639, lat: 22.5726 },
    details: "High thermal inertia of colonial masonry with relentless tropical humidity.",
    action_label: "Inspect Hotspot",
    action_type: "xai",
  },

  // ==========================================
  // LEVEL 3: DISTRICT PINS (Localized Neighborhood / Ward-Level Pins)
  // Visible when a particular district is clicked!
  // ==========================================

  // --- MUMBAI DISTRICT LOCALIZED NEIGHBORHOODS ---
  {
    id: "PIN_DIS_MUM_001",
    type: "hotspot",
    name: "Dharavi Hotspot",
    heat_risk: 88,
    lst_celsius: 42.0,
    tree_count: 840,
    tree_source: "BMC Tree Census 2024 (Ward G/North)",
    population: "High",
    level: "district",
    parentId: "mumbai",
    districtId: "mumbai",
    coordinates: { lng: 72.856, lat: 19.043 },
    details: "Dense unshaded tin-roof settlements with low solar albedo and extreme thermal re-radiation.",
    action_label: "Inspect",
    action_type: "xai",
  },
  {
    id: "PIN_DIS_MUM_002",
    type: "low_veg",
    name: "Mithi River Low Vegetation Zone",
    heat_risk: 81,
    lst_celsius: 40.5,
    tree_count: 320,
    tree_source: "BMC Environment Dept & Sentinel-2",
    population: "Moderate",
    level: "district",
    parentId: "mumbai",
    districtId: "mumbai",
    coordinates: { lng: 72.871, lat: 19.062 },
    details: "Severely degraded mangrove embankment lacking urban tree cover, amplifying radiant heat.",
    action_label: "Inspect",
    action_type: "whatif",
  },
  {
    id: "PIN_DIS_MUM_003",
    type: "water_needed",
    name: "Kurla Transit Camp Water Facility Needed",
    heat_risk: 84,
    lst_celsius: 43.1,
    tree_count: 510,
    tree_source: "BMC Ward L Water Registry",
    population: "High",
    level: "district",
    parentId: "mumbai",
    districtId: "mumbai",
    coordinates: { lng: 72.88, lat: 19.068 },
    details: "High pedestrian transit volume with zero operational drinking water dispensers within 400m.",
    action_label: "Inspect",
    action_type: "whatif",
  },
  {
    id: "PIN_DIS_MUM_004",
    type: "cooling_centre",
    name: "Chhota Sion Hospital Cooling Centre",
    heat_risk: 42,
    lst_celsius: 36.2,
    tree_count: 1450,
    tree_source: "BMC Health Infrastructure Census",
    population: "250 Beds AC",
    level: "district",
    parentId: "mumbai",
    districtId: "mumbai",
    coordinates: { lng: 72.861, lat: 19.039 },
    details: "Air-conditioned emergency thermal respite center equipped with medical dehydration staff and ORS.",
    action_label: "Inspect",
    action_type: "coolpath",
  },
  {
    id: "PIN_DIS_MUM_005",
    type: "citizen_report",
    name: "Govandi Station Citizen Distress Report",
    heat_risk: 86,
    lst_celsius: 42.8,
    tree_count: 410,
    tree_source: "BMC Ward M/East Census",
    population: "Critical Distress",
    level: "district",
    parentId: "mumbai",
    districtId: "mumbai",
    coordinates: { lng: 72.915, lat: 19.055 },
    details: "Crowdsourced report: Multiple informal transit laborers fainted from heat exhaustion.",
    action_label: "Inspect",
    action_type: "report",
  },
  {
    id: "PIN_DIS_MUM_006",
    type: "vulnerability",
    name: "Mankhurd Informal Cluster High Vulnerability",
    heat_risk: 91,
    lst_celsius: 44.5,
    tree_count: 290,
    tree_source: "BMC Urban Planning Census",
    population: "High Elderly & Child Ratio",
    level: "district",
    parentId: "mumbai",
    districtId: "mumbai",
    coordinates: { lng: 72.93, lat: 19.05 },
    details: "Extreme socio-demographic vulnerability with acute tin-roof density and high infant heat sensitivity.",
    action_label: "Inspect",
    action_type: "xai",
  },

  // --- PUNE DISTRICT LOCALIZED NEIGHBORHOODS ---
  {
    id: "PIN_DIS_PUN_001",
    type: "hotspot",
    name: "Hadapsar Industrial Heat Zone",
    heat_risk: 86,
    lst_celsius: 42.6,
    tree_count: 1100,
    tree_source: "PMC Urban Forestry (Hadapsar)",
    population: "High",
    level: "district",
    parentId: "pune",
    districtId: "pune",
    coordinates: { lng: 73.928, lat: 18.502 },
    details: "Industrial metal roofs and dense transit intersections causing elevated asphalt heating.",
    action_label: "Inspect",
    action_type: "xai",
  },
  {
    id: "PIN_DIS_PUN_002",
    type: "cooling_centre",
    name: "Sassoon General Hospital Heat Ward",
    heat_risk: 41,
    lst_celsius: 36.4,
    tree_count: 3200,
    tree_source: "PMC Health Dept",
    population: "450 Beds AC",
    level: "district",
    parentId: "pune",
    districtId: "pune",
    coordinates: { lng: 73.874, lat: 18.528 },
    details: "Central regional cooling hub with rapid misting facilities and heatstroke ambulance dispatch.",
    action_label: "Inspect",
    action_type: "coolpath",
  },
  {
    id: "PIN_DIS_PUN_003",
    type: "low_veg",
    name: "Kothrud Urban Concrete Basin",
    heat_risk: 74,
    lst_celsius: 40.8,
    tree_count: 2100,
    tree_source: "PMC Tree Census (Ward 12)",
    population: "Moderate",
    level: "district",
    parentId: "pune",
    districtId: "pune",
    coordinates: { lng: 73.815, lat: 18.507 },
    details: "High residential building density with insufficient street canopy cover.",
    action_label: "Inspect",
    action_type: "whatif",
  },
  {
    id: "PIN_DIS_PUN_004",
    type: "water_needed",
    name: "Shivajinagar Bus Stand Hydration Deficit",
    heat_risk: 82,
    lst_celsius: 41.5,
    tree_count: 850,
    tree_source: "PMC Ward 5 Water Registry",
    population: "Critical Transit",
    level: "district",
    parentId: "pune",
    districtId: "pune",
    coordinates: { lng: 73.852, lat: 18.531 },
    details: "Massive passenger footfall exposed to afternoon heat without adequate chilled water stations.",
    action_label: "Inspect",
    action_type: "whatif",
  },

  // --- NAGPUR DISTRICT LOCALIZED NEIGHBORHOODS ---
  {
    id: "PIN_DIS_NAG_001",
    type: "hotspot",
    name: "Sitabuldi Market Basalt Hotspot",
    heat_risk: 94,
    lst_celsius: 46.8,
    tree_count: 620,
    tree_source: "NMC Tree Census (Zone 2)",
    population: "Severe",
    level: "district",
    parentId: "nagpur",
    districtId: "nagpur",
    coordinates: { lng: 79.083, lat: 21.144 },
    details: "Severe dry heat furnace with asphalt temperatures crossing 55°C during afternoon peaks.",
    action_label: "Inspect",
    action_type: "xai",
  },
  {
    id: "PIN_DIS_NAG_002",
    type: "cooling_centre",
    name: "Nagpur Government Medical College Respite",
    heat_risk: 45,
    lst_celsius: 38.1,
    tree_count: 2400,
    tree_source: "NMC Health Infrastructure",
    population: "550 Beds AC",
    level: "district",
    parentId: "nagpur",
    districtId: "nagpur",
    coordinates: { lng: 79.098, lat: 21.127 },
    details: "Dedicated heat action casualty wing with intravenous fluid hydration and active ice cooling.",
    action_label: "Inspect",
    action_type: "coolpath",
  },

  // --- JAIPUR DISTRICT LOCALIZED NEIGHBORHOODS ---
  {
    id: "PIN_DIS_JAI_001",
    type: "hotspot",
    name: "Johari Bazaar Sandstone Radiance",
    heat_risk: 92,
    lst_celsius: 46.5,
    tree_count: 580,
    tree_source: "Jaipur Nagar Nigam Census",
    population: "High",
    level: "district",
    parentId: "jaipur",
    districtId: "jaipur",
    coordinates: { lng: 75.827, lat: 26.921 },
    details: "Historic stone facades store and re-radiate intense solar energy through evening hours.",
    action_label: "Inspect",
    action_type: "xai",
  },
  {
    id: "PIN_DIS_JAI_002",
    type: "cooling_centre",
    name: "SMS Hospital Thermal Respite Hub",
    heat_risk: 46,
    lst_celsius: 38.5,
    tree_count: 3100,
    tree_source: "SMS Medical College Census",
    population: "900 Beds AC",
    level: "district",
    parentId: "jaipur",
    districtId: "jaipur",
    coordinates: { lng: 75.817, lat: 26.896 },
    details: "Comprehensive desert heat emergency triage unit with specialized heatstroke protocols.",
    action_label: "Inspect",
    action_type: "coolpath",
  },
];

module.exports = { SEED_PINS };
